version: '3'

services:
  php:
    container_name: php
    build: ./docker/files/php
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
    depends_on:
      - mysql
      - redis
      - memcached
    links:
      - mysql:mysql
      - redis:redis
      - memcached:memcached
  nginx:
    container_name: nginx
    image: nginx:1.17.9
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    links:
      - php
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.6
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./share:/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: redis:3.0.6
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
  memcached:
    container_name: memcached
    image: memcached:1.4.23
    restart: always
    expose:
      - "11211"
    ports:
      - "11211:11211"
    volumes:
      - ./docker/data/memcached:/data
