version: '3'
networks:
  lnmp-net:
    driver: bridge

services:
  php5:
    container_name: php5
    build: ./docker/files/php5
    tty: true
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
    networks:
      - lnmp-net

  php7:
    container_name: php7
    build: ./docker/files/php7
    tty: true
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
    networks:
      - lnmp-net

  nginx:
    container_name: nginx
    image: nginx:1.17.9
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      # - php5
      - php7
    networks:
      - lnmp-net

  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./share:/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - lnmp-net

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - lnmp-net
