version: '3'

services:
  cgi:
    container_name: cgi
    build: ./docker/files/cgi
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/cgi:/var/log/php-fpm
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
  proxy:
    container_name: proxy
    build: ./docker/files/proxy
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./docker/config/proxy/conf.d:/etc/nginx/conf.d
      - ./docker/log/proxy:/var/log/nginx
    depends_on:
      - cgi
    links:
      - cgi
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.6
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes