version: '3'
networks:
  lan_access:
    driver: bridge

services:
  php5:
    container_name: php5
    build: ./docker/files/php5
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
    networks:
      - lan_access
      - default

  php7:
    container_name: php7
    build: ./docker/files/php7
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/php:/var/log/php-fpm
    networks:
      - lan_access
      - default

  nginx:
    container_name: nginx
    image: nginx:1.17.9
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php5
      - php7
    links:
      - php5
      - php7
    networks:
      - lan_access
      - default

  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./share:/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: redis:3.0.6
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
  memcached:
    container_name: memcached
    image: memcached:1.4.23
    restart: always
    expose:
      - "11211"
    ports:
      - "11211:11211"
    volumes:
      - ./docker/data/memcached:/data
