version: '3'

services:
  cgi:
    container_name: cgi
    image: phpdockerio/php56-fpm
    tty: true
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/data/www
      - ./docker/log/cgi:/var/log/php-fpm
    depends_on:
      - mysql
      - redis
      - elasticsearch
      - memcached
    links:
      - mysql:mysql
      - redis:redis
      - elasticsearch:elasticsearch
      - memcached:memcached
  proxy:
    container_name: proxy
    image: nginx:1.17.9
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/data/www
      - ./docker/config/proxy/conf.d:/etc/nginx/conf.d
      - ./docker/log/proxy:/var/log/nginx
    depends_on:
      - cgi
    links:
      - cgi
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.6
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    container_name: redis
    image: redis:3.0.6
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.5.2
    restart: always
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./docker/config/elasticsearch:/etc/elasticsearch
      - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
  memcached:
    container_name: memcached
    image: memcached:1.4.23
    restart: always
    expose:
      - "11211"
    ports:
      - "11211:11211"
    volumes:
      - ./docker/data/memcached:/data
  kibana:
    container_name: kibana
    image: kibana:5.5.2
    restart: always
    expose:
      - "5601"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch